-- MySQL Script generated by MySQL Workbench
-- 04/06/15 14:19:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oman_tourism_guide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oman_tourism_guide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oman_tourism_guide` DEFAULT CHARACTER SET utf8 ;
USE `oman_tourism_guide` ;

-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`admin_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`admin_type` (
  `admintype_id` INT(11) NOT NULL AUTO_INCREMENT,
  `admintype_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admintype_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`admin` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT,
  `admin_type` INT(11) NOT NULL,
  `admin_email` VARCHAR(100) NOT NULL,
  `admin_name` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(65) NOT NULL,
  `admin_create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_id`, `admin_type`),
  INDEX `admintype_id_key_idx` (`admin_type` ASC),
  CONSTRAINT `admintype_id_key`
    FOREIGN KEY (`admin_type`)
    REFERENCES `oman_tourism_guide`.`admin_type` (`admintype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`language` (
  `lang_id` INT(11) NOT NULL AUTO_INCREMENT,
  `lang_name` VARCHAR(45) NULL DEFAULT NULL,
  `lang_shortcut` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`lang_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(160) NOT NULL,
  `user_lang` INT(11) NOT NULL,
  `user_email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC),
  CONSTRAINT `lang_id_key`
    FOREIGN KEY (`user_id`)
    REFERENCES `oman_tourism_guide`.`language` (`lang_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`feadback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`feadback` (
  `feadback_id` INT(11) NOT NULL AUTO_INCREMENT,
  `feadback_user_id` INT(11) NOT NULL,
  `feadback_add_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `feadback_text` TEXT NOT NULL,
  PRIMARY KEY (`feadback_id`, `feadback_user_id`),
  INDEX `feadback_userid_key_idx` (`feadback_user_id` ASC),
  CONSTRAINT `feadback_userid_key`
    FOREIGN KEY (`feadback_user_id`)
    REFERENCES `oman_tourism_guide`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`place_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`place_type` (
  `place_id` INT(11) NOT NULL AUTO_INCREMENT,
  `place_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`place_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`place` (
  `place_id` INT(11) NOT NULL AUTO_INCREMENT,
  `place_type` INT(11) NOT NULL,
  `place_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(132) NULL DEFAULT NULL,
  `place_location_lat` FLOAT NULL DEFAULT NULL,
  `place_location_lng` FLOAT NULL DEFAULT NULL,
  `place_admin_creator` INT(11) NOT NULL,
  `view` INT(1) NOT NULL DEFAULT '1',
  `description` TEXT NOT NULL,
  `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`place_id`, `place_type`, `place_admin_creator`),
  INDEX `place_type_id_idx` (`place_type` ASC),
  INDEX `place_admin_creator_id_idx` (`place_admin_creator` ASC),
  CONSTRAINT `place_admin_creator_id`
    FOREIGN KEY (`place_admin_creator`)
    REFERENCES `oman_tourism_guide`.`admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `place_ibfk_1`
    FOREIGN KEY (`place_type`)
    REFERENCES `oman_tourism_guide`.`place_type` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 153
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`item_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`item_type` (
  `itemtype_id` INT(11) NOT NULL AUTO_INCREMENT,
  `itemtype_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`itemtype_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`item` (
  `item_id` INT(11) NOT NULL AUTO_INCREMENT,
  `item_type` INT(11) NOT NULL,
  `item_admin_creator` INT(11) NOT NULL,
  `item_place` INT(11) NOT NULL,
  `item_name` VARCHAR(45) NOT NULL,
  `item_add_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `item_description` TEXT NOT NULL,
  PRIMARY KEY (`item_id`, `item_type`, `item_place`, `item_admin_creator`),
  INDEX `item_place_key_idx` (`item_place` ASC),
  INDEX `item_admin_key_idx` (`item_admin_creator` ASC),
  INDEX `item_itemtype_key_idx` (`item_type` ASC),
  CONSTRAINT `item_admin_key`
    FOREIGN KEY (`item_admin_creator`)
    REFERENCES `oman_tourism_guide`.`admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_place_key`
    FOREIGN KEY (`item_place`)
    REFERENCES `oman_tourism_guide`.`place` (`place_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `item_itemtype_key`
    FOREIGN KEY (`item_type`)
    REFERENCES `oman_tourism_guide`.`item_type` (`itemtype_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`item_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`item_comment` (
  `itemcomment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `itemcomment_item_id` INT(11) NOT NULL,
  `itemcomment_user_id` INT(11) NOT NULL,
  `itemcomment_text` TEXT NOT NULL,
  `itemcomment_add_date` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`itemcomment_id`, `itemcomment_item_id`, `itemcomment_user_id`),
  INDEX `item_id_key_idx` (`itemcomment_item_id` ASC),
  INDEX `itemcomment_user_id_idx` (`itemcomment_user_id` ASC),
  CONSTRAINT `itemcomment_id_key`
    FOREIGN KEY (`itemcomment_item_id`)
    REFERENCES `oman_tourism_guide`.`item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `itemcomment_user_id`
    FOREIGN KEY (`itemcomment_user_id`)
    REFERENCES `oman_tourism_guide`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`service_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`service_type` (
  `servicetype_id` INT(11) NOT NULL,
  `servicetype_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`servicetype_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`user_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`user_service` (
  `useservice_id` INT(11) NOT NULL AUTO_INCREMENT,
  `useservice_name` VARCHAR(45) NULL DEFAULT NULL,
  `useservice_email` VARCHAR(45) NULL DEFAULT NULL,
  `useservice_phone` VARCHAR(45) NULL DEFAULT NULL,
  `useservice_password` VARCHAR(45) NULL DEFAULT NULL,
  `useservice_add_date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`useservice_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`service` (
  `service_id` INT(11) NOT NULL AUTO_INCREMENT,
  `service_type` INT(11) NOT NULL,
  `service_user_id` INT(11) NOT NULL,
  `service_admin_add` INT(11) NOT NULL,
  `service_location` VARCHAR(45) NULL DEFAULT NULL,
  `service_desc` TEXT NULL DEFAULT NULL,
  `service_add_date` TIMESTAMP NULL DEFAULT NULL,
  `service_rate` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`service_id`, `service_type`, `service_admin_add`, `service_user_id`),
  INDEX `service_type_key_idx` (`service_type` ASC),
  INDEX `service_admin_key_idx` (`service_admin_add` ASC),
  INDEX `service_user_key_idx` (`service_user_id` ASC),
  CONSTRAINT `service_admin_key`
    FOREIGN KEY (`service_admin_add`)
    REFERENCES `oman_tourism_guide`.`admin` (`admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_type_key`
    FOREIGN KEY (`service_type`)
    REFERENCES `oman_tourism_guide`.`service_type` (`servicetype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `service_user_key`
    FOREIGN KEY (`service_user_id`)
    REFERENCES `oman_tourism_guide`.`user_service` (`useservice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`service_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`service_request` (
  `servicerequest_id` INT(11) NOT NULL AUTO_INCREMENT,
  `servicerequest_type` INT(11) NOT NULL,
  `servicerequest_user_id` INT(11) NOT NULL,
  `servicerequest__location` VARCHAR(45) NOT NULL,
  `servicerequest_desc` TEXT NOT NULL,
  `servicerequest_add_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`servicerequest_id`, `servicerequest_type`, `servicerequest_user_id`),
  INDEX `service_type_key_idx` (`servicerequest_type` ASC),
  INDEX `service_user_key_idx` (`servicerequest_user_id` ASC),
  CONSTRAINT `servicerequest_type_key`
    FOREIGN KEY (`servicerequest_type`)
    REFERENCES `oman_tourism_guide`.`service_type` (`servicetype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `servicerequest_user_key`
    FOREIGN KEY (`servicerequest_user_id`)
    REFERENCES `oman_tourism_guide`.`user_service` (`useservice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`share_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`share_area` (
  `sharearea_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sharearea_text` TEXT NULL DEFAULT NULL,
  `sharearea_user_id` INT(11) NOT NULL,
  `sharearea_image` LONGBLOB NULL DEFAULT NULL,
  `sharearea_add_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sharearea_location` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`sharearea_id`, `sharearea_user_id`),
  INDEX `sharearea_userid_key_idx` (`sharearea_user_id` ASC),
  CONSTRAINT `sharearea_userid_key`
    FOREIGN KEY (`sharearea_user_id`)
    REFERENCES `oman_tourism_guide`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`share_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`share_comment` (
  `sharecomm_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sharecomm_sharearea_id` INT(11) NULL DEFAULT NULL,
  `sharecomm_user_id` INT(11) NOT NULL,
  `sharecomm_add_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `sharecomm_text` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`sharecomm_id`, `sharecomm_user_id`),
  INDEX `sharecomm_userid_key_idx` (`sharecomm_user_id` ASC),
  CONSTRAINT `sharecomm_sharearea_id_key`
    FOREIGN KEY (`sharecomm_id`)
    REFERENCES `oman_tourism_guide`.`share_area` (`sharearea_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sharecomm_userid_key`
    FOREIGN KEY (`sharecomm_user_id`)
    REFERENCES `oman_tourism_guide`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `oman_tourism_guide`.`item_image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oman_tourism_guide`.`item_image` (
  `id_item_image` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT(11) NOT NULL,
  `image_url` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_item_image`, `item_id`),
  INDEX `item_image_key_idx` (`item_id` ASC),
  CONSTRAINT `item_image_key`
    FOREIGN KEY (`item_id`)
    REFERENCES `oman_tourism_guide`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
